// <auto-generated />
using System;
using AiHub.Connector.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AiHub.Connector.Migrations
{
    [DbContext(typeof(ConnectorDbContext))]
    partial class ConnectorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("AiHub.Connector.Data.Entities.ExternalFileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoxFileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalItemId")
                        .IsUnique();

                    b.HasIndex("RoxFileId")
                        .IsUnique();

                    b.ToTable("ExternalFiles");
                });

            modelBuilder.Entity("AiHub.Connector.Data.Entities.ExternalGroupEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalGroupId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KnowledgePoolId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalGroupId")
                        .IsUnique();

                    b.HasIndex("KnowledgePoolId")
                        .IsUnique();

                    b.ToTable("ExternalGroups");
                });

            modelBuilder.Entity("AiHub.Connector.Data.Entities.FileKnowledgePoolEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("KnowledgePoolId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoxFileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoxFileId", "KnowledgePoolId")
                        .IsUnique();

                    b.ToTable("FileKnowledgePools");
                });
#pragma warning restore 612, 618
        }
    }
}

